# -*- coding: utf-8 -*-
"""DBSCAN Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jHhY5KlqUpBpff_STWWC5i_2_L7-hRCR
"""

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

df=pd.read_csv("Mall_Customers.csv")

df.head()

df.isnull().sum()

df.drop('CustomerID',axis=1,inplace=True)

df

df.isnull().any()

df['Genre'].replace(('Male','Female'),(0,1),inplace=True)

df.head()

x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

from sklearn.cluster import DBSCAN
cluster=DBSCAN()
model=cluster.fit(x)

labels=cluster.labels_

labels

from sklearn import metrics

#identifying the points which makes up our core points
sample_cores=np.zeros_like(labels,dtype=bool)

sample_cores[cluster.core_sample_indices_]=True

#Calculating the number of clusters

n_clusters=len(set(labels))- (1 if -1 in labels else 0)



print(metrics.silhouette_score(x,labels))

